apiVersion: v1
kind: Secret

metadata:
  name: my-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository

stringData:
  type: git
  url: https://github.com/moura1001/nlw-unite-devops.git
